config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/:id' => 'users#show'
  root 'articles#index'
  resources :articles do
      post 'add' =>  'favorites#create'
      delete 'add' => 'favorites#destroy'
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :articles, through: :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :move_to_index ,except: [:index, :show]
  before_action :set_article, only: [:show, :destroy, :edit, :update]

  def index
    @articles = Article.includes(:users).order("created_at DESC")
    @latest_articles = Article.includes(:users).order("created_at DESC").limit(4)
  end

  def new
    @article = Article.new
  end

  def create
    Article.create(article_params)
    redirect_to action: :index
  end

  def show
  end

  def destroy
    @article.destroy if @article.user_id.to_i == current_user.id.to_i
    redirect_to action: :index
  end

  def edit
  end

  def update
    @article.update(article_params) if @article.user_id.to_i == current_user.id.to_i
    redirect_to action: :show
  end

  private
  def article_params
    params.require(:article).permit(:title, :image, :text).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    article = Article.find(params[:article_id])
    if Favorite.create(user_id: current_user.id.to_i, article_id: article.id)
      redirect_to article_path(article.id)
    else
      redirect_to root_url
    end

  end

  def destroy
      article = Article.find(params[:article_id])
      if favorite = Favorite.find_by(user_id: current_user.id.to_i, article_id: article.id)
        favorite.delete
        redirect_to article_path(article.id)
      else
        redirect_to root_url
      end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @favorites = Favorite.where(user_id: @user.id)
    @counts = @favorites.length
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="col s12 m6 fadein">
  <div class="card">
    <div class="card-image">
      <object class="object-image index_img" data="<%= article.image %>">
          <div class="noImage index_img"><span style="color:#bdbdbd;">No image</span></div>
      </object>

      <span class="card-title textOverflow overTitle"><%= article.title %></span>
    </div>
    <div class="card-content">
      <div class="chip">
        <i class="mini material-icons">today</i>
        <span class="tipDate"><%= article.created_at.strftime('%Y.%m.%d') %></span>
      </div>
      <div class="chip">
        <i class="mini material-icons">person</i>
        <span class="tipDate"><%= User.find(article.user_id.to_i).nickname %></span>
      </div>
      <div class="chip">
        <i class="mini material-icons">favorite</i>
        <span class="tipDate"><%= article.favorite_ids.length %></span>
      </div>
      <p class="textOverflow detailText"><%= article.text %></p>
    </div>
    <div class="card-action">
      <%= link_to "続き", "/articles/#{article.id}", class: "btn waves-effect miniButton", data: {"turbolinks" => false} %>
      <% if user_signed_in? && article.user_id.to_i == current_user.id.to_i %>
        <%= link_to "編集", "/articles/#{article.id}/edit", class: "btn waves-effect grey lighten-4 grey-text text-darken-2", data: {"turbolinks" => false} %>
        <%= link_to "削除", "/articles/#{article.id}", class: "btn waves-effect grey lighten-4 grey-text text-darken-2", method: :"delete", data: {"turbolinks" => false} %>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h2 class="article_title">投稿内容を編集する</h2>
  <%= form_for(@article) do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :title %>
        <%= f.label :title, class: "active" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :image %>
        <%= f.label :image, class: "active" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_area :text, class: "materialize-textarea" %>
        <%= f.label :text, class: "active" %>
      </div>
    </div>

    <div class="row">
    <%= button_tag type: "submit", class: "btn waves-effect btn-large wideButton" do %>編集内容を反映<% end %>
    </div>

  <% end %>

app/views/articles/index.html.erb
<div class="cp_cssslider">
  <div class="cp_slidewrapper">
    <% @latest_articles.each do |article| %>
      <div class="cp_slide_item"><a href="/articles/<%= article.id %>" data-turbolinks="false"><img src="<%= article.image %>"></a></div>
    <% end %>
  </div>
</div>

<% @articles.each do |article| %>
  <%= render partial: "article", locals: { article: article } %>
<% end %>

app/views/articles/new.html.erb
<h2 class="article_title">投稿フォーム</h2>
  <%= form_for(@article) do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :title, placeholder: "タイトルを入力！" %>
        <%= f.label :title, class: "active" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :image, placeholder: "画像のURLを貼り付けよう！" %>
        <%= f.label :image, class: "active" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.text_area :text, placeholder: '記事の本文を入力してね！', class: "materialize-textarea" %>
        <%= f.label :text, class: "active" %>
      </div>
    </div>

    <div class="row">
    <%= button_tag type: "submit", class: "btn waves-effect btn-large wideButton" do %>投稿する<% end %>
    </div>

  <% end %>

app/views/articles/show.html.erb
<div class="col s12 m12">
  <div class="card">
    <div class="card-image">
      <object style="width:100%;display: block;" data="<%= @article.image %>">
          <div class="noImage index_img"><span style="color:#bdbdbd;">No image</span></div>
      </object>
      <span class="card-title textOverflow overTitle"><%= @article.title %></span>
    </div>
    <div class="card-content">
      <div class="chip">
        <i class="mini material-icons">today</i>
        <span class="tipDate"><%= @article.created_at.strftime('%Y.%m.%d') %></span>
      </div>
      <div class="chip">
        <i class="mini material-icons">person_pin</i>
        <span class="tipDate"><%= User.find(@article.user_id.to_i).nickname %></span>
      </div>
      <div class="chip">
        <i class="mini material-icons">favorite</i>
        <span class="tipDate"><%= @article.favorite_ids.length %></span>
      </div>
      <%= simple_format(@article.text, class: 'detailText') %>
    </div>
    <% if user_signed_in? %>
      <div class="card-action">
        <% if user_signed_in? && @article.user_id.to_i == current_user.id.to_i %>
          <%= link_to "編集", "/articles/#{@article.id}/edit", class: "btn waves-effect grey lighten-4 grey-text text-darken-2" %>
          <%= link_to "削除", "/articles/#{@article.id}", class: "btn waves-effect grey lighten-4 grey-text text-darken-2", method: :"delete" %>
        <% end %>
        <% if !Favorite.exists?(user_id: current_user.id, article_id:@article.id ) %>
          <%= link_to "お気に入り", article_add_path(@article), class: "btn waves-effect grey lighten-4 grey-text text-darken-2", method: :post %>
          <% else %>
          <%= link_to "お気に入り解除", article_add_path(@article), class: "btn waves-effect grey lighten-4 grey-text text-darken-2", method: :delete %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= csrf_meta_tags %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Pacifico">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
</head>
<body class="grey lighten-5">
  <div class="navbar-fixed">
    <nav class="changeColor">
      <div class="nav-wrapper container">
        <%= link_to "BlogApp", root_path, class: "brand-logo left siteName", data: {"turbolinks" => false} %>
        <ul class="right">
          <% if user_signed_in? %>
            <li><a href="/users/<%= current_user.id %>" data-turbolinks="false"><i class="mini material-icons">favorite</i></a></li>
            <li><a href="/articles/new" data-turbolinks="false"><i class="mini material-icons">create</i></a></li>
            <!-- <li><%= link_to "投稿", new_article_path, data: {"turbolinks" => false} %></li> -->
            <li><%= link_to "LogOut", destroy_user_session_path, method: :"delete", data: {"turbolinks" => false} %></li>
          <% else %>
            <li><%= link_to "ログイン", new_user_session_path, data: {"turbolinks" => false} %></li>
            <li><%= link_to "会員登録", new_user_registration_path, data: {"turbolinks" => false} %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
  <ul class="theme">
    <div class="container">
      <li class="changePink" style="background: #e7d4d7;">PINK</li>
      <li class="changeBlue waves-effect">BLUE</li>
      <li class="changeGreen waves-effect">GREEN</li>
    </div>
  </ul>
  <div class="container center grey-text">Please choose your favorite color！</div>
  <div class="container">
    <div class="section">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </div>
  <footer class="grey lighten-3">© 2018 <span class="siteName">BlogApp</span></footer>
</body>
</html>

app/views/users/show.html.erb
<div style="min-height:600px">
  <h2 class="article_title"><%= @user.nickname %>のお気に入り</h2>
  <% if @counts !=0 %>
    <% @favorites.each do |favorite| %>
      <%= render partial: "articles/article", locals: { article: Article.find(favorite.article_id) } %>
    <% end %>
  <% else %>
    <div class="detailText row">まだお気に入りはありません。みんなの投稿をみてお気に入りを見つけましょう！</div>
    <div class="btn btn-large wideButton"><a href="/articles" class="white-text" data-turbolinks="false">みんなの投稿をみる</a></div>
  <% end %>
</div>